### ISSUE TITLE
Cloudformation does not surface error messages generated by Transfer Family on `InvalidRequestException`

### ISSUE THREAD

**Issue by mayurm88** [aws-cloudformation/aws-cloudformation-resource-providers-transfer#37]
### Reproduction Steps

1. Create an AS2 certificate using a Cloudformation stack
2. Create an AS2 profile and use the certificate id generated in Step 1 as a certificate in the profile.
3. Delete the Cloudformation stack created in Step 1.
4. We get an `InvalidRequest` error code in Cloudformation which does not have any information about what is wrong with the request.

<img width="2381" alt="Screenshot 2023-01-02 at 2 02 27 PM" src="https://user-images.githubusercontent.com/75965317/210270250-812f1b27-882e-46d5-bf9b-d9c9901e5bed.png">

The error in Cloudtrail does have the correct error message.

<img width="2757" alt="Screenshot 2023-01-02 at 2 05 49 PM" src="https://user-images.githubusercontent.com/75965317/210270532-e9ad1202-5511-4e71-b5e9-638cd8919108.png">

**Comment by aws-sde** [comment]
Resolved by https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-transfer/pull/42
