### ISSUE TITLE
Ability to stop and start a server

### ISSUE THREAD

**Issue by Rizxcviii** [aws-cloudformation/aws-cloudformation-resource-providers-transfer#46]
A feature available in transfer family and is available through the AWS SDK is to [stop](https://docs.aws.amazon.com/transfer/latest/userguide/API_StopServer.html) and [start](https://docs.aws.amazon.com/transfer/latest/userguide/API_StartServer.html) transfer family server when required. This is not currently supported by Cloudformation

**Comment by aws-sde** [comment]
Closing this issue in favour of the issue opened in the coverage roadmap repository, which had a response https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1779#issuecomment-1701318408
